export const FLAPPY_TARGETS = Object.freeze([
  "asdf",
  "jkl;",
  "fj",
  "dk",
  "sa",
  "lk",
]);

export const FLAPPY_CONFIG = Object.freeze({
  width: 960,
  height: 560,
  fixedStepMs: 16,
  maximumFrameMs: 240,
  birdX: 250,
  birdRadius: 18,
  initialBirdY: 280,
  gravity: 420,
  impulseVelocity: -185,
  maximumUpwardVelocity: -280,
  gateWidth: 86,
  gateGap: 220,
  gateSpeed: 140,
  gateSpacing: 420,
  initialGateX: 720,
  targetActivationX: 860,
  minimumGapCenter: 165,
  maximumGapCenter: 395,
  initialGateCount: 4,
  pointsPerGate: 100,
  gatesPerMultiplier: 2,
  maximumMultiplier: 4,
  maximumTargetTokens: 6,
  difficulty: "beginner",
  targets: FLAPPY_TARGETS,
});
