export const qwertyLayers = [
    [
        ["Esc", "Escape"],
        ["F1", ""],
        ["F2", ""],
        ["F3", ""],
        ["F4", ""],
        ["F5", ""],
        ["F6", ""],
        ["F7", ""],
        ["F8", ""],
        ["F9", ""],
        ["F10", ""],
        ["F11", ""],
        ["F12",  ""],
        ["Druck", ""],
        ["Roll", ""],
        ["Pause", ""],

        ["Esc", "Escape"],
        ["1", "Digit1"],
        ["2", "Digit2"],
        ["3", "Digit3"],
        ["4", "Digit4"],
        ["5", "Digit5"],
        ["6", "Digit6"],
        ["7", "Digit7"],
        ["8", "Digit8"],
        ["9", "Digit9"],
        ["0", "Digit0"],
        ["ß", "Minus"],
        ["´", "Equal"],
        ["Backspace", "Backspace"],

        ["Einfg", "Equal"],
        ["Pos1", "Equal"],
        ["Bild↑", "Equal"],

        ["Num", "Equal"],
        ["/", "Equal"],
        ["*", "Equal"],
        ["-", "Equal"],

        ["Tab", "Tab"],
        ["q", "KeyQ"],
        ["w", "KeyW"],
        ["e", "KeyE"],
        ["r", "KeyR"],
        ["t", "KeyT"],
        ["z", "KeyY"],
        ["u", "KeyU"],
        ["i", "KeyI"],
        ["o", "KeyO"],
        ["p", "KeyP"],
        ["ü", "BracketLeft"],
        ["+", "BracketRight"],
        ["⏎", "Enter"],

        ["Entf", "Equal"],
        ["Ende", "Equal"],
        ["Bild↓", "Equal"],

        ["7", "Equal"],
        ["8", "Equal"],
        ["9", "Equal"],
        ["+", "Equal"],

        ["Caps", "CapsLock"],
        ["a", "KeyA"],
        ["s", "KeyS"],
        ["d", "KeyD"],
        ["f", "KeyF"],
        ["g", "KeyG"],
        ["h", "KeyH"],
        ["j", "KeyJ"],
        ["k", "KeyK"],
        ["l", "KeyL"],
        ["ö", "Semicolon"],
        ["ä", "Quote"],
        ["#", "Quote"],
        

        ["4", "Equal"],
        ["5", "Equal"],
        ["6", "Equal"],


        ["Shift", "ShiftLeft"],
        ["<", "KeyZ"],
        ["y", "KeyZ"],
        ["x", "KeyX"],
        ["c", "KeyC"],
        ["v", "KeyV"],
        ["b", "KeyB"],
        ["n", "KeyN"],
        ["m", "KeyM"],
        [",", "Comma"],
        [".", "Period"],
        ["-", "Slash"],
        ["Shift", "ShiftRight"],

        ["↑", "Equal"], 

        ["1", ""], 
        ["2", ""],
        ["3", ""],
        ["⏎", ""],

        ["Ctrl", "ControlLeft"],
        ["Win", "MetaLeft"],
        ["Alt", "AltLeft"],
        ["Space", "Space"],
        ["Alt", "AltRight"],
        ["Fn", "Fn"],
        ["Menu", "ContextMenu"],
        ["Ctrl", "ControlRight"],

        ["←", "Equal"],
        ["↓", "Equal"],
        ["→", "Equal"],

        ["0", "Equal"],
        [",", "Equal"],

    ],
];

const qwertyKeysLayout = [

    { row: 0, col: 0, cls: "function" },
    { row: 0, col: 1.5 },
    { row: 0, col: 2.5 },
    { row: 0, col: 3.5 },
    { row: 0, col: 4.5 },
    { row: 0, col: 6 },
    { row: 0, col: 7 },
    { row: 0, col: 8 },
    { row: 0, col: 9 },
    { row: 0, col: 10.5 },
    { row: 0, col: 11.5 },
    { row: 0, col: 12.5 },
    { row: 0, col: 13.5, w: 1 },
    
    { row: 0, col: 15.3, w: 1, cls: "action" },
    { row: 0, col: 16.3, w: 1, cls: "action" },
    { row: 0, col: 17.3, w: 1, cls: "action" },

    { row: 1.3, col: 0, cls: "function" },
    { row: 1.3, col: 1 },
    { row: 1.3, col: 2 },
    { row: 1.3, col: 3 },
    { row: 1.3, col: 4 },
    { row: 1.3, col: 5 },
    { row: 1.3, col: 6 },
    { row: 1.3, col: 7 },
    { row: 1.3, col: 8 },
    { row: 1.3, col: 9 },
    { row: 1.3, col: 10 },
    { row: 1.3, col: 11 },
    { row: 1.3, col: 12, w: 1 },
    { row: 1.3, col: 13, w: 1.9, cls: "action" },

    { row: 1.3, col: 15.3 },
    { row: 1.3, col: 16.3 },
    { row: 1.3, col: 17.3 },

    { row: 1.3, col: 18.5 },
    { row: 1.3, col: 19.5 },
    { row: 1.3, col: 20.5 },
    { row: 1.3, col: 21.5 },

    { row: 2.3, col: 0, w: 2, cls: "action" },
    { row: 2.3, col: 2 },
    { row: 2.3, col: 3 },
    { row: 2.3, col: 4 },
    { row: 2.3, col: 5 },
    { row: 2.3, col: 6 },
    { row: 2.3, col: 7 },
    { row: 2.3, col: 8 },
    { row: 2.3, col: 9 },
    { row: 2.3, col: 10 },
    { row: 2.3, col: 11 },
    { row: 2.3, col: 12 },
    { row: 2.3, col: 13 },
    { row: 2.3, col: 14, w: 1, h: 2, cls: "action" },

    { row: 2.3, col: 15.3 },
    { row: 2.3, col: 16.3 },
    { row: 2.3, col: 17.3 },

    { row: 2.3, col: 18.5 },
    { row: 2.3, col: 19.5 },
    { row: 2.3, col: 20.5 },
    { row: 2.3, col: 21.5, h: 2 },

    { row: 3.3, col: 0, w: 1.8, cls: "action" },
    { row: 3.3, col: 1.8 },
    { row: 3.3, col: 2.8 },
    { row: 3.3, col: 3.8 },
    { row: 3.3, col: 4.8 },
    { row: 3.3, col: 5.8 },
    { row: 3.3, col: 6.8 },
    { row: 3.3, col: 7.8 },
    { row: 3.3, col: 8.8 },
    { row: 3.3, col: 9.8 },
    { row: 3.3, col: 10.8 },
    { row: 3.3, col: 11.8 },
    { row: 3.3, col: 12.8 },
    

    { row: 3.3, col: 18.5 },
    { row: 3.3, col: 19.5 },
    { row: 3.3, col: 20.5 },

    { row: 4.3, col: 0, w: 1.2, cls: "action" },
    { row: 4.3, col: 1.3 },
    { row: 4.3, col: 2.3 },
    { row: 4.3, col: 3.3 },
    { row: 4.3, col: 4.3 },
    { row: 4.3, col: 5.3 },
    { row: 4.3, col: 6.3 },
    { row: 4.3, col: 7.3 },
    { row: 4.3, col: 8.3 },
    { row: 4.3, col: 9.3 },
    { row: 4.3, col: 10.3 },
    { row: 4.3, col: 11.3 },
    { row: 4.3, col: 12.3, w: 2.7, cls: "action" },
    
    { row: 4.3, col: 16.3 },

    { row: 4.3, col: 18.5 },
    { row: 4.3, col: 19.5 },
    { row: 4.3, col: 20.5 },
    { row: 4.3, col: 21.5, h: 2 },

    { row: 5.3, col: 0, w: 1.5, cls: "action" },
    { row: 5.3, col: 1.5, w: 1.2, cls: "action" },
    { row: 5.3, col: 2.7, w: 1.3, cls: "action" },
    { row: 5.3, col: 4, w: 6, cls: "action space" },
    { row: 5.3, col: 10, w: 1.3, cls: "action" },
    { row: 5.3, col: 11.3, w: 1.1, cls: "action" },
    { row: 5.3, col: 12.4, w: 1.3, cls: "action" },
    { row: 5.3, col: 13.7, w: 1.5, cls: "action" },

    { row: 5.3, col: 15.3, w: 1, cls: "action" },
    { row: 5.3, col: 16.3, w: 1, cls: "action" },
    { row: 5.3, col: 17.3, w: 1, cls: "action" },

    { row: 5.3, col: 18.5, w: 2 },
    { row: 5.3, col: 20.5 },  
];

const getQwertyKeys = () => {
    const result = [];
    qwertyKeysLayout.forEach((k, key) => {
        result.push({ ...k, label: qwertyLayers[0][key][0], code: qwertyLayers[0][key][1] });
    });

    return result;
};

export const qwertyLayout = {
    name: "QWERTY",
    keySize: { w: 53, h: 50, gap: 2 },
    keys: getQwertyKeys(),
};
