export const magicLayers = [
  [
    ["Esc", "Escape"],
    ["F1", "F1"],
    ["F2", "F2"],
    ["F3", "F3"],
    ["F4", "F4"],
    ["F5", "F5"],
    ["F6", "F6"],
    ["F7", "F7"],
    ["F8", "F8"],
    ["F9", "F9"],
    ["F10", "F10"],
    ["F11", "F11"],
    ["F12", "F12"],
    ["F13", "F13"],
    ["F14", "F14"],
    ["F15", "F15"],

    ["F16", "F16"],
    ["F17", "F17"],
    ["F18", "F18"],
    ["F19", "F19"],

    ["^", "Unknown(10)"],
    ["1", "Num1"],
    ["2", "Num2"],
    ["3", "Num3"],
    ["4", "Num4"],
    ["5", "Num5"],
    ["6", "Num6"],
    ["7", "Num7"],
    ["8", "Num8"],
    ["9", "Num9"],
    ["0", "Num0"],
    ["ß", "Minus"],
    ["´", "Equal"],
    ["⌫", "Backspace"],

    ["Einfg", "Insert"],
    ["Pos1", "Home"],
    ["Bild↑", "PageUp"],

    ["Num", "NumLock"],
    ["/", "KpDivide"],
    ["*", "KpMultiply"],
    ["-", "KpMinus"],

    ["Tab", "Tab"],
    ["q", "KeyQ"],
    ["w", "KeyW"],
    ["e", "KeyE"],
    ["r", "KeyR"],
    ["t", "KeyT"],
    ["z", "KeyY"],
    ["u", "KeyU"],
    ["i", "KeyI"],
    ["o", "KeyO"],
    ["p", "KeyP"],
    ["ü", "LeftBracket"],
    ["+", "RightBracket"],
    ["⏎", "Return"],

    ["Entf", "Delete"],
    ["Ende", "End"],
    ["Bild↓", "PageDown"],

    ["7", "Kp7"],
    ["8", "Kp8"],
    ["9", "Kp9"],
    ["+", "KpPlus"],

    ["Caps", "CapsLock"],
    ["a", "KeyA"],
    ["s", "KeyS"],
    ["d", "KeyD"],
    ["f", "KeyF"],
    ["g", "KeyG"],
    ["h", "KeyH"],
    ["j", "KeyJ"],
    ["k", "KeyK"],
    ["l", "KeyL"],
    ["ö", "SemiColon"],
    ["ä", "Quote"],
    ["#", "BackSlash"],

    ["4", "Kp4"],
    ["5", "Kp5"],
    ["6", "Kp6"],
    ["+", "Kp6"],

    ["Shift", "ShiftLeft"],
    ["<", "IntlBackslash"],
    ["y", "KeyZ"],
    ["x", "KeyX"],
    ["c", "KeyC"],
    ["v", "KeyV"],
    ["b", "KeyB"],
    ["n", "KeyN"],
    ["m", "KeyM"],
    [",", "Comma"],
    [".", "Dot"],
    ["-", "Slash"],
    ["Shift", "ShiftRight"],

    ["↑", "UpArrow"],

    ["1", "Kp1"],
    ["2", "Kp2"],
    ["3", "Kp3"],
    ["⏎", "KpReturn"],

    ["Ctrl", "ControlLeft"],
    ["Win", "MetaLeft"],
    ["Alt", "Alt"],
    ["Space", "Space"],
    ["Alt", "AltGr"],
    ["Menu", "Unknown135"],
    ["Ctrl", "ControlRight"],

    ["←", "LeftArrow"],
    ["↓", "DownArrow"],
    ["→", "RightArrow"],

    ["0", "Kp0"],
    [",", "KpDelete"],
  ],
];

const qwertyKeysLayout = [
  { row: 0, col: 0, w: 1.5, cls: "function" },
  { row: 0, col: 1.5 },
  { row: 0, col: 2.5 },
  { row: 0, col: 3.5 },
  { row: 0, col: 4.5 },
  { row: 0, col: 5.5 },
  { row: 0, col: 6.5 },
  { row: 0, col: 7.5 },
  { row: 0, col: 8.5 },
  { row: 0, col: 9.5 },
  { row: 0, col: 10.5 },
  { row: 0, col: 11.5 },
  { row: 0, col: 12.5 },

  { row: 0, col: 15 },
  { row: 0, col: 16 },
  { row: 0, col: 17 },

  { row: 0, col: 18.5 },
  { row: 0, col: 19.5 },
  { row: 0, col: 20.5 },
  { row: 0, col: 21.5 },

  { row: 1, col: 0, cls: "function" },
  { row: 1, col: 1 },
  { row: 1, col: 2 },
  { row: 1, col: 3 },
  { row: 1, col: 4 },
  { row: 1, col: 5 },
  { row: 1, col: 6 },
  { row: 1, col: 7 },
  { row: 1, col: 8 },
  { row: 1, col: 9 },
  { row: 1, col: 10 },
  { row: 1, col: 11 },
  { row: 1, col: 12, w: 1 },
  { row: 1, col: 13, w: 1.5 },

  { row: 1, col: 15 },
  { row: 1, col: 16 },
  { row: 1, col: 17 },

  { row: 1, col: 18.5 },
  { row: 1, col: 19.5 },
  { row: 1, col: 20.5 },
  { row: 1, col: 21.5 },

  { row: 2, col: 0, w: 1.5 },
  { row: 2, col: 1.5 },
  { row: 2, col: 2.5 },
  { row: 2, col: 3.5 },
  { row: 2, col: 4.5 },
  { row: 2, col: 5.5 },
  { row: 2, col: 6.5 },
  { row: 2, col: 7.5 },
  { row: 2, col: 8.5 },
  { row: 2, col: 9.5 },
  { row: 2, col: 10.5 },
  { row: 2, col: 11.5 },
  { row: 2, col: 12.5 },
  { row: 2, col: 13.5, w: 1, h: 2 },

  { row: 2, col: 15 },
  { row: 2, col: 16 },
  { row: 2, col: 17 },

  { row: 2, col: 18.5 },
  { row: 2, col: 19.5 },
  { row: 2, col: 20.5 },
  { row: 2, col: 21.5 },

  { row: 3, col: 0, w: 1.5 },
  { row: 3, col: 1.5 },
  { row: 3, col: 2.5 },
  { row: 3, col: 3.5 },
  { row: 3, col: 4.5 },
  { row: 3, col: 5.5 },
  { row: 3, col: 6.5 },
  { row: 3, col: 7.5 },
  { row: 3, col: 8.5 },
  { row: 3, col: 9.5 },
  { row: 3, col: 10.5 },
  { row: 3, col: 11.5 },
  { row: 3, col: 12.5 },

  { row: 3, col: 18.5 },
  { row: 3, col: 19.5 },
  { row: 3, col: 20.5 },
  { row: 3, col: 21.5 },

  { row: 4, col: 0, w: 1.2 },
  { row: 4, col: 1.3 },
  { row: 4, col: 2.3 },
  { row: 4, col: 3.3 },
  { row: 4, col: 4.3 },
  { row: 4, col: 5.3 },
  { row: 4, col: 6.3 },
  { row: 4, col: 7.3 },
  { row: 4, col: 8.3 },
  { row: 4, col: 9.3 },
  { row: 4, col: 10.3 },
  { row: 4, col: 11.3 },
  { row: 4, col: 12.3, w: 2.2 },

  { row: 4, col: 16 },

  { row: 4, col: 18.5 },
  { row: 4, col: 19.5 },
  { row: 4, col: 20.5 },
  { row: 4, col: 21.5, h: 2 },

  { row: 5, col: 0, w: 1.5 },
  { row: 5, col: 1.5, w: 1.2 },
  { row: 5, col: 2.7, w: 1.3 },
  { row: 5, col: 4, w: 6 },
  { row: 5, col: 10, w: 1.5 },
  { row: 5, col: 11.5, w: 1.5 },
  { row: 5, col: 13, w: 1.5 },

  { row: 5, col: 15, w: 1 },
  { row: 5, col: 16, w: 1 },
  { row: 5, col: 17, w: 1 },

  { row: 5, col: 18.5, w: 2 },
  { row: 5, col: 20.5 },
];

const getMagicKeys = () => {
  const result = [];
  qwertyKeysLayout.forEach((k, key) => {
    result.push({
      ...k,
      label: magicLayers[0][key][0],
      code: magicLayers[0][key][1],
    });
  });

  return result;
};

export const magicLayout = {
  name: "Magic Keyboard",
  keySize: { w: 53, h: 50, gap: 2 },
  keys: getMagicKeys(),
};
