export const corneLayers = [[
    ["Tab", "Tab"],
    ["q", "KeyQ"],
    ["w", "KeyW"],
    ["e", "KeyE"],
    ["r", "KeyR"],
    ["t", "KeyT"],
    ["z", "KeyY"],
    ["u", "KeyU"],
    ["i", "KeyI"],
    ["o", "KeyO"],
    ["p", "KeyP"],
    ["BSPC", "BSPC"],

    ["Ctrl", "ControlLeft"],
    ["a", "KeyA"],
    ["s", "KeyS"],
    ["d", "KeyD"],
    ["f", "KeyF"],
    ["g", "KeyG"],
    ["h", "KeyH"],
    ["j", "KeyJ"],
    ["k", "KeyK"],
    ["l", "KeyL"],
    ["ö", "Quote"],
    ["/", "Slash"],

    ["Shift", "ShiftLeft"],
    ["y", "KeyY"],
    ["x", "KeyX"],
    ["c", "KeyC"],
    ["v", "KeyV"],
    ["b", "KeyB"],
    ["n", "KeyN"],
    ["m", "KeyM"],
    [",", "Comma"],
    [".", "Period"],
    ["/", "Slash"],


    ["ESC", "ESC"],
    ["GUI", "Space"],
    ["Low", "Space"],
    ["SPACE", "Enter"],
    ["ENTER", "Space"],
    ["Up", "Space"],
    ["ALT", "Backspace"],
],
[
    null,
    ["Q", "KeyQ"],
    ["W", "KeyW"],
    ["E", "KeyE"],
    ["R", "KeyR"],
    ["T", "KeyT"],
    ["Z", "KeyY"],
    ["U", "KeyU"],
    ["I", "KeyI"],
    ["O", "KeyO"],
    ["P", "KeyP"],
    null,
    null,
    ["A", "KeyA"],
    ["S", "KeyS"],
    ["D", "KeyD"],
    ["F", "KeyF"],
    ["G", "KeyG"],
    ["H", "KeyH"],
    ["J", "KeyJ"],
    ["K", "KeyK"],
    ["L", "KeyL"],
    ["Ö", "KeyL"],
    null,
    null,
    ["Y", "KeyY"],
    ["X", "KeyX"],
    ["C", "KeyC"],
    ["V", "KeyV"],
    ["B", "KeyB"],
    ["N", "KeyM"],
    ["M", "KeyM"],
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
],
[
    null,
    ["Й", "KeyQ"],
    ["Ц", "KeyW"],
    ["У", "KeyE"],
    ["К", "KeyR"],
    ["Е", "KeyT"],
    ["Н", "KeyY"],
    ["Г", "KeyU"],
    ["Ш", "KeyI"],
    ["Щ", "KeyO"],
    ["З", "KeyP"],
    null,
    null,
    ["Ф", "KeyA"],
    ["Ы", "KeyS"],
    ["В", "KeyD"],
    ["А", "KeyF"],
    ["П", "KeyG"],
    ["Р", "KeyH"],
    ["О", "KeyJ"],
    ["О", "KeyK"],
    ["Л", "KeyL"],
    ["Д", "KeyL"],
    null,
    null,
    ["Я", "KeyY"],
    ["Ч", "KeyX"],
    ["С", "KeyC"],
    ["М", "KeyV"],
    ["И", "KeyB"],
    ["Т", "KeyM"],
    ["Ь", "KeyM"],
    ["Б", "KeyM"],
    ["Ю", "KeyM"],
    [".", "KeyM"],
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
],
[
    null,
    ["Й", "KeyQ"],
    ["Ц", "KeyW"],
    ["У", "KeyE"],
    ["К", "KeyR"],
    ["Е", "KeyT"],
    ["Н", "KeyY"],
    ["Г", "KeyU"],
    ["Ш", "KeyI"],
    ["Щ", "KeyO"],
    ["З", "KeyP"],
    null,
    null,
    ["Ф", "KeyA"],
    ["Ы", "KeyS"],
    ["В", "KeyD"],
    ["А", "KeyF"],
    ["П", "KeyG"],
    null,
    ["←", "KeyJ"],
    ["↓", "KeyK"],
    ["↑", "KeyL"],
    ["→", "KeyL"],
    null,
    ["BT Clr", "KeyY"],
    ["BT1", "KeyY", "assets/images/linux-logo-penguin.png"],
    ["BT2", "KeyX", "assets/images/apple_rainbow.png"],
    ["BT3", "KeyC", "assets/images/android-logo.png"],
    ["BT4", "KeyV"],
    ["BT5", "KeyB"],
    ["Т", "KeyM"],
    ["Ь", "KeyM"],
    ["Б", "KeyM"],
    ["Ю", "KeyM"],
    [".", "KeyM"],
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
],
[
    ["CAPS", "KeyQ"],
    ["!", "KeyW"],
    ["@", "KeyE"],
    ["#", "KeyR"],
    ["$", "KeyT"],
    ["%", "KeyY"],
    ["^", "KeyU"],
    ["&", "KeyI"],
    ["*", "KeyO"],
    ["(", "KeyP"],
    [")", "KeyP"],
    ["BSPC", "KeyA"],
    ["CTRL", "KeyS"],
    ["-", "KeyD"],
    ["=", "KeyF"],
    ["[", "KeyG"],
    ["]", "KeyG"],
    ["\\", "KeyG"],
    ["←", "KeyJ"],
    ["↓", "KeyK"],
    ["↑", "KeyL"],
    ["→", "KeyL"],
    null,
    ["BT Clr", "KeyY"],
    ["BT1", "KeyY"],
    ["BT2", "KeyX"],
    ["BT3", "KeyC"],
    ["BT4", "KeyV"],
    ["BT5", "KeyB"],
    ["Т", "KeyM"],
    ["Ь", "KeyM"],
    ["Б", "KeyM"],
    ["Ю", "KeyM"],
    [".", "KeyM"],
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
]
];

const corneKeysLayout = [
    { row: 0, col: 1 },
    { row: 0, col: 2 },
    { row: 0, col: 3 },
    { row: 0, col: 4 },
    { row: 0, col: 5 },
    { row: 0, col: 6 },
    { row: 0, col: 10 },
    { row: 0, col: 11 },
    { row: 0, col: 12 },
    { row: 0, col: 13 },
    { row: 0, col: 14 },
    { row: 0, col: 15 },

    { row: 1, col: 1 },
    { row: 1, col: 2 },
    { row: 1, col: 3 },
    { row: 1, col: 4 },
    { row: 1, col: 5 },
    { row: 1, col: 6 },
    { row: 1, col: 10 },
    { row: 1, col: 11 },
    { row: 1, col: 12 },
    { row: 1, col: 13 },
    { row: 1, col: 14 },
    { row: 1, col: 15 },

    { row: 2, col: 1 },
    { row: 2, col: 2 },
    { row: 2, col: 3 },
    { row: 2, col: 4 },
    { row: 2, col: 5 },
    { row: 2, col: 6 },
    { row: 2, col: 10 },
    { row: 2, col: 11 },
    { row: 2, col: 12 },
    { row: 2, col: 13 },
    { row: 2, col: 14 },
    { row: 2, col: 15 },

    { row: 3.2, col: 5, cls: "action" },
    { row: 3.2, col: 6, cls: "action" },
    { row: 3.2, col: 7, cls: "action" },
    { row: 3.2, col: 9, cls: "action" },
    { row: 3.2, col: 10, cls: "action" },
    { row: 3.2, col: 11, cls: "action" },
];

const getCorneKeys = () => {
    const result = [];
    corneKeysLayout.forEach((k, key) => {
        const [label, code, image] = corneLayers[0][key];
        const labelValue = image ? { text: label, image } : label;
        result.push({ ...k, label: labelValue, code });
    });

    return result;
};

export const corneLayout = {
    name: "Corne (split)",
    keySize: { w: 57, h: 45, gap: 10 },
    keys: getCorneKeys(),
};
