export const qwertyLayers = [
    [
        ["Esc", "Escape"],
        ["F1", "F1"],
        ["F2", "F2"],
        ["F3", "F3"],
        ["F4", "F4"],
        ["F5", "F5"],
        ["F6", "F6"],
        ["F7", "F7"],
        ["F8", "F8"],
        ["F9", "F9"],
        ["F10", "F10"],
        ["F11", "F11"],
        ["F12",  "F12"],
        ["Druck", "PrintScreen"],
        ["Roll", "ScrollLock"],
        ["Pause", "Pause"],

        ["Esc", "Escape"],
        ["1", "Num1"],
        ["2", "Num2"],
        ["3", "Num3"],
        ["4", "Num4"],
        ["5", "Num5"],
        ["6", "Num6"],
        ["7", "Num7"],
        ["8", "Num8"],
        ["9", "Num9"],
        ["0", "Num0"],
        ["ß", "Minus"],
        ["´", "Equal"],
        ["Backspace", "Backspace"],

        ["Einfg", "Insert"],
        ["Pos1", "Home"],
        ["Bild↑", "PageUp"],

        ["Num", "NumLock"],
        ["/", "KpDivide"],
        ["*", "KpMultiply"],
        ["-", "KpMinus"],

        ["Tab", "Tab"],
        ["q", "KeyQ"],
        ["w", "KeyW"],
        ["e", "KeyE"],
        ["r", "KeyR"],
        ["t", "KeyT"],
        ["z", "KeyY"],
        ["u", "KeyU"],
        ["i", "KeyI"],
        ["o", "KeyO"],
        ["p", "KeyP"],
        ["ü", "LeftBracket"],
        ["+", "RightBracket"],
        ["⏎", "Return"],

        ["Entf", "Delete"],
        ["Ende", "End"],
        ["Bild↓", "PageDown"],

        ["7", "Kp7"],
        ["8", "Kp8"],
        ["9", "Kp9"],
        ["+", "KpPlus"],

        ["Caps", "CapsLock"],
        ["a", "KeyA"],
        ["s", "KeyS"],
        ["d", "KeyD"],
        ["f", "KeyF"],
        ["g", "KeyG"],
        ["h", "KeyH"],
        ["j", "KeyJ"],
        ["k", "KeyK"],
        ["l", "KeyL"],
        ["ö", "SemiColon"],
        ["ä", "Quote"],
        ["#", "BackSlash"],
        

        ["4", "Kp4"],
        ["5", "Kp5"],
        ["6", "Kp6"],


        ["Shift", "ShiftLeft"],
        ["<", "IntlBackslash"],
        ["y", "KeyZ"],
        ["x", "KeyX"],
        ["c", "KeyC"],
        ["v", "KeyV"],
        ["b", "KeyB"],
        ["n", "KeyN"],
        ["m", "KeyM"],
        [",", "Comma"],
        [".", "Dot"],
        ["-", "Slash"],
        ["Shift", "ShiftRight"],

        ["↑", "UpArrow"], 

        ["1", "Kp1"], 
        ["2", "Kp2"],
        ["3", "Kp3"],
        ["⏎", "KpReturn"],

        ["Ctrl", "ControlLeft"],
        ["Win", "MetaLeft"],
        ["Alt", "Alt"],
        ["Space", "Space"],
        ["Alt", "AltGr"],
        ["Win", "Unknown134"],
        ["Menu", "Unknown135"],
        ["Ctrl", "ControlRight"],

        ["←", "LeftArrow"],
        ["↓", "DownArrow"],
        ["→", "RightArrow"],

        ["0", "Kp0"],
        [",", "KpDelete"],

    ],
];

const qwertyKeysLayout = [

    { row: 0, col: 0, cls: "function" },
    { row: 0, col: 1.5 },
    { row: 0, col: 2.5 },
    { row: 0, col: 3.5 },
    { row: 0, col: 4.5 },
    { row: 0, col: 6 },
    { row: 0, col: 7 },
    { row: 0, col: 8 },
    { row: 0, col: 9 },
    { row: 0, col: 10.5 },
    { row: 0, col: 11.5 },
    { row: 0, col: 12.5 },
    { row: 0, col: 13.5, w: 1 },
    
    { row: 0, col: 15.3, w: 1, cls: "action" },
    { row: 0, col: 16.3, w: 1, cls: "action" },
    { row: 0, col: 17.3, w: 1, cls: "action" },

    { row: 1.3, col: 0, cls: "function" },
    { row: 1.3, col: 1 },
    { row: 1.3, col: 2 },
    { row: 1.3, col: 3 },
    { row: 1.3, col: 4 },
    { row: 1.3, col: 5 },
    { row: 1.3, col: 6 },
    { row: 1.3, col: 7 },
    { row: 1.3, col: 8 },
    { row: 1.3, col: 9 },
    { row: 1.3, col: 10 },
    { row: 1.3, col: 11 },
    { row: 1.3, col: 12, w: 1 },
    { row: 1.3, col: 13, w: 1.9, cls: "action" },

    { row: 1.3, col: 15.3 },
    { row: 1.3, col: 16.3 },
    { row: 1.3, col: 17.3 },

    { row: 1.3, col: 18.5 },
    { row: 1.3, col: 19.5 },
    { row: 1.3, col: 20.5 },
    { row: 1.3, col: 21.5 },

    { row: 2.3, col: 0, w: 2, cls: "action" },
    { row: 2.3, col: 2 },
    { row: 2.3, col: 3 },
    { row: 2.3, col: 4 },
    { row: 2.3, col: 5 },
    { row: 2.3, col: 6 },
    { row: 2.3, col: 7 },
    { row: 2.3, col: 8 },
    { row: 2.3, col: 9 },
    { row: 2.3, col: 10 },
    { row: 2.3, col: 11 },
    { row: 2.3, col: 12 },
    { row: 2.3, col: 13 },
    { row: 2.3, col: 14, w: 1, h: 2, cls: "action" },

    { row: 2.3, col: 15.3 },
    { row: 2.3, col: 16.3 },
    { row: 2.3, col: 17.3 },

    { row: 2.3, col: 18.5 },
    { row: 2.3, col: 19.5 },
    { row: 2.3, col: 20.5 },
    { row: 2.3, col: 21.5, h: 2 },

    { row: 3.3, col: 0, w: 1.8, cls: "action" },
    { row: 3.3, col: 1.8 },
    { row: 3.3, col: 2.8 },
    { row: 3.3, col: 3.8 },
    { row: 3.3, col: 4.8 },
    { row: 3.3, col: 5.8 },
    { row: 3.3, col: 6.8 },
    { row: 3.3, col: 7.8 },
    { row: 3.3, col: 8.8 },
    { row: 3.3, col: 9.8 },
    { row: 3.3, col: 10.8 },
    { row: 3.3, col: 11.8 },
    { row: 3.3, col: 12.8 },
    

    { row: 3.3, col: 18.5 },
    { row: 3.3, col: 19.5 },
    { row: 3.3, col: 20.5 },

    { row: 4.3, col: 0, w: 1.2, cls: "action" },
    { row: 4.3, col: 1.3 },
    { row: 4.3, col: 2.3 },
    { row: 4.3, col: 3.3 },
    { row: 4.3, col: 4.3 },
    { row: 4.3, col: 5.3 },
    { row: 4.3, col: 6.3 },
    { row: 4.3, col: 7.3 },
    { row: 4.3, col: 8.3 },
    { row: 4.3, col: 9.3 },
    { row: 4.3, col: 10.3 },
    { row: 4.3, col: 11.3 },
    { row: 4.3, col: 12.3, w: 2.7, cls: "action" },
    
    { row: 4.3, col: 16.3 },

    { row: 4.3, col: 18.5 },
    { row: 4.3, col: 19.5 },
    { row: 4.3, col: 20.5 },
    { row: 4.3, col: 21.5, h: 2 },

    { row: 5.3, col: 0, w: 1.5, cls: "action" },
    { row: 5.3, col: 1.5, w: 1.2, cls: "action" },
    { row: 5.3, col: 2.7, w: 1.3, cls: "action" },
    { row: 5.3, col: 4, w: 6, cls: "action space" },
    { row: 5.3, col: 10, w: 1.3, cls: "action" },
    { row: 5.3, col: 11.3, w: 1.1, cls: "action" },
    { row: 5.3, col: 12.4, w: 1.3, cls: "action" },
    { row: 5.3, col: 13.7, w: 1.5, cls: "action" },

    { row: 5.3, col: 15.3, w: 1, cls: "action" },
    { row: 5.3, col: 16.3, w: 1, cls: "action" },
    { row: 5.3, col: 17.3, w: 1, cls: "action" },

    { row: 5.3, col: 18.5, w: 2 },
    { row: 5.3, col: 20.5 },  
];

const getQwertyKeys = () => {
    const result = [];
    qwertyKeysLayout.forEach((k, key) => {
        result.push({ ...k, label: qwertyLayers[0][key][0], code: qwertyLayers[0][key][1] });
    });

    return result;
};

export const qwertyLayout = {
    name: "QWERTY",
    keySize: { w: 53, h: 50, gap: 2 },
    keys: getQwertyKeys(),
};
