export const qwertyLayers = [
    [
        ["Esc", "Escape"],
        ["1", "Digit1"],
        ["2", "Digit2"],
        ["3", "Digit3"],
        ["4", "Digit4"],
        ["5", "Digit5"],
        ["6", "Digit6"],
        ["7", "Digit7"],
        ["8", "Digit8"],
        ["9", "Digit9"],
        ["0", "Digit0"],
        ["-", "Minus"],
        ["=", "Equal"],
        ["Backspace", "Backspace"],

        ["Tab", "Tab"],
        ["q", "KeyQ"],
        ["w", "KeyW"],
        ["e", "KeyE"],
        ["r", "KeyR"],
        ["t", "KeyT"],
        ["z", "KeyY"],
        ["u", "KeyU"],
        ["i", "KeyI"],
        ["o", "KeyO"],
        ["p", "KeyP"],
        ["[", "BracketLeft"],
        ["]", "BracketRight"],
        ["\\", "Backslash"],
        ["Caps", "CapsLock"],
        ["a", "KeyA"],
        ["s", "KeyS"],
        ["d", "KeyD"],
        ["f", "KeyF"],
        ["g", "KeyG"],
        ["h", "KeyH"],
        ["j", "KeyJ"],
        ["k", "KeyK"],
        ["l", "KeyL"],
        [";", "Semicolon"],
        ["'", "Quote"],
        ["Enter", "Enter"],
        ["Shift", "ShiftLeft"],
        ["z", "KeyZ"],
        ["x", "KeyX"],
        ["c", "KeyC"],
        ["v", "KeyV"],
        ["b", "KeyB"],
        ["n", "KeyN"],
        ["m", "KeyM"],
        [",", "Comma"],
        [".", "Period"],
        ["/", "Slash"],
        ["Shift", "ShiftRight"],
        ["Ctrl", "ControlLeft"],
        ["Win", "MetaLeft"],
        ["Alt", "AltLeft"],
        ["Space", "Space"],
        ["Alt", "AltRight"],
        ["Fn", "Fn"],
        ["Menu", "ContextMenu"],
        ["Ctrl", "ControlRight"],
    ],
];

const qwertyKeysLayout = [
    { row: 0, col: 0, cls: "function" },
    { row: 0, col: 1 },
    { row: 0, col: 2 },
    { row: 0, col: 3 },
    { row: 0, col: 4 },
    { row: 0, col: 5 },
    { row: 0, col: 6 },
    { row: 0, col: 7 },
    { row: 0, col: 8 },
    { row: 0, col: 9 },
    { row: 0, col: 10 },
    { row: 0, col: 11 },
    { row: 0, col: 12 },
    { row: 0, col: 13, w: 2, cls: "action" },
    { row: 1, col: 0, w: 1.5, cls: "action" },
    { row: 1, col: 1.5 },
    { row: 1, col: 2.5 },
    { row: 1, col: 3.5 },
    { row: 1, col: 4.5 },
    { row: 1, col: 5.5 },
    { row: 1, col: 6.5 },
    { row: 1, col: 7.5 },
    { row: 1, col: 8.5 },
    { row: 1, col: 9.5 },
    { row: 1, col: 10.5 },
    { row: 1, col: 11.5 },
    { row: 1, col: 12.5 },
    { row: 1, col: 13.5, w: 1.5, cls: "action" },
    { row: 2, col: 0, w: 1.8, cls: "action" },
    { row: 2, col: 1.8 },
    { row: 2, col: 2.8 },
    { row: 2, col: 3.8 },
    { row: 2, col: 4.8 },
    { row: 2, col: 5.8 },
    { row: 2, col: 6.8 },
    { row: 2, col: 7.8 },
    { row: 2, col: 8.8 },
    { row: 2, col: 9.8 },
    { row: 2, col: 10.8 },
    { row: 2, col: 11.8 },
    { row: 2, col: 12.8, w: 2.2, cls: "action" },
    { row: 3, col: 0, w: 2.3, cls: "action" },
    { row: 3, col: 2.3 },
    { row: 3, col: 3.3 },
    { row: 3, col: 4.3 },
    { row: 3, col: 5.3 },
    { row: 3, col: 6.3 },
    { row: 3, col: 7.3 },
    { row: 3, col: 8.3 },
    { row: 3, col: 9.3 },
    { row: 3, col: 10.3 },
    { row: 3, col: 11.3 },
    { row: 3, col: 12.3, w: 2.7, cls: "action" },
    { row: 4, col: 0, w: 1.5, cls: "action" },
    { row: 4, col: 1.5, w: 1.2, cls: "action" },
    { row: 4, col: 2.7, w: 1.3, cls: "action" },
    { row: 4, col: 4, w: 6, cls: "action space" },
    { row: 4, col: 10, w: 1.3, cls: "action" },
    { row: 4, col: 11.3, w: 1.1, cls: "action" },
    { row: 4, col: 12.4, w: 1.3, cls: "action" },
    { row: 4, col: 13.7, w: 1.5, cls: "action" },
];

const getQwertyKeys = () => {
    const result = [];
    qwertyKeysLayout.forEach((k, key) => {
        result.push({ ...k, label: qwertyLayers[0][key][0], code: qwertyLayers[0][key][1] });
    });

    return result;
};

export const qwertyLayout = {
    name: "QWERTY",
    keySize: { w: 60, h: 63, gap: 5 },
    keys: getQwertyKeys(),
};
